version: '3'
services:
  nginx:
    image: nginx:1.21
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:80
    links:
      - app
    depends_on:
      - app
  app:
    build:
      context: .
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - RAILS_ENV=development
    links:
      - pg
    command: bundle exec puma
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
