version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - RAILS_ENV=development
    links:
      - pg
    ports:
      - 3000:3000
    command: bundle exec puma
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
